################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_dhcp_user_class.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_dns.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_emb_mqtt_client.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_firmware_upgradation.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_ftp.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_http_client.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_mdnsd.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_mqtt_client.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_multicast.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_ota_fw_up.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_pop3_client.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_raw_data.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_smtp_client.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_sntp_client.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_web_socket.c 

OBJS += \
./sapis/nwk/applications/rsi_dhcp_user_class.o \
./sapis/nwk/applications/rsi_dns.o \
./sapis/nwk/applications/rsi_emb_mqtt_client.o \
./sapis/nwk/applications/rsi_firmware_upgradation.o \
./sapis/nwk/applications/rsi_ftp.o \
./sapis/nwk/applications/rsi_http_client.o \
./sapis/nwk/applications/rsi_mdnsd.o \
./sapis/nwk/applications/rsi_mqtt_client.o \
./sapis/nwk/applications/rsi_multicast.o \
./sapis/nwk/applications/rsi_ota_fw_up.o \
./sapis/nwk/applications/rsi_pop3_client.o \
./sapis/nwk/applications/rsi_raw_data.o \
./sapis/nwk/applications/rsi_smtp_client.o \
./sapis/nwk/applications/rsi_sntp_client.o \
./sapis/nwk/applications/rsi_web_socket.o 

C_DEPS += \
./sapis/nwk/applications/rsi_dhcp_user_class.d \
./sapis/nwk/applications/rsi_dns.d \
./sapis/nwk/applications/rsi_emb_mqtt_client.d \
./sapis/nwk/applications/rsi_firmware_upgradation.d \
./sapis/nwk/applications/rsi_ftp.d \
./sapis/nwk/applications/rsi_http_client.d \
./sapis/nwk/applications/rsi_mdnsd.d \
./sapis/nwk/applications/rsi_mqtt_client.d \
./sapis/nwk/applications/rsi_multicast.d \
./sapis/nwk/applications/rsi_ota_fw_up.d \
./sapis/nwk/applications/rsi_pop3_client.d \
./sapis/nwk/applications/rsi_raw_data.d \
./sapis/nwk/applications/rsi_smtp_client.d \
./sapis/nwk/applications/rsi_sntp_client.d \
./sapis/nwk/applications/rsi_web_socket.d 


# Each subdirectory must supply rules for building sources it contributes
sapis/nwk/applications/rsi_dhcp_user_class.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_dhcp_user_class.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_dhcp_user_class.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_dns.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_dns.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_dns.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_emb_mqtt_client.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_emb_mqtt_client.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_emb_mqtt_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_firmware_upgradation.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_firmware_upgradation.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_firmware_upgradation.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_ftp.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_ftp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_ftp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_http_client.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_http_client.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_http_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_mdnsd.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_mdnsd.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_mdnsd.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_mqtt_client.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_mqtt_client.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_mqtt_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_multicast.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_multicast.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_multicast.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_ota_fw_up.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_ota_fw_up.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_ota_fw_up.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_pop3_client.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_pop3_client.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_pop3_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_raw_data.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_raw_data.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_raw_data.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_smtp_client.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_smtp_client.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_smtp_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_sntp_client.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_sntp_client.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_sntp_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/nwk/applications/rsi_web_socket.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/rsi_web_socket.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/nwk/applications/rsi_web_socket.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

