################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_ble_gap_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_ble_gatt_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_ble_l2cap_conn.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_a2dp_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_avrcp_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_common_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_gap_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_hfp_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_hid_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_iap_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_pbap_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_sdp_apis.c \
C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_spp_apis.c 

OBJS += \
./sapis/bt_ble/rsi_ble_gap_apis.o \
./sapis/bt_ble/rsi_ble_gatt_apis.o \
./sapis/bt_ble/rsi_ble_l2cap_conn.o \
./sapis/bt_ble/rsi_bt_a2dp_apis.o \
./sapis/bt_ble/rsi_bt_avrcp_apis.o \
./sapis/bt_ble/rsi_bt_common_apis.o \
./sapis/bt_ble/rsi_bt_gap_apis.o \
./sapis/bt_ble/rsi_bt_hfp_apis.o \
./sapis/bt_ble/rsi_bt_hid_apis.o \
./sapis/bt_ble/rsi_bt_iap_apis.o \
./sapis/bt_ble/rsi_bt_pbap_apis.o \
./sapis/bt_ble/rsi_bt_sdp_apis.o \
./sapis/bt_ble/rsi_bt_spp_apis.o 

C_DEPS += \
./sapis/bt_ble/rsi_ble_gap_apis.d \
./sapis/bt_ble/rsi_ble_gatt_apis.d \
./sapis/bt_ble/rsi_ble_l2cap_conn.d \
./sapis/bt_ble/rsi_bt_a2dp_apis.d \
./sapis/bt_ble/rsi_bt_avrcp_apis.d \
./sapis/bt_ble/rsi_bt_common_apis.d \
./sapis/bt_ble/rsi_bt_gap_apis.d \
./sapis/bt_ble/rsi_bt_hfp_apis.d \
./sapis/bt_ble/rsi_bt_hid_apis.d \
./sapis/bt_ble/rsi_bt_iap_apis.d \
./sapis/bt_ble/rsi_bt_pbap_apis.d \
./sapis/bt_ble/rsi_bt_sdp_apis.d \
./sapis/bt_ble/rsi_bt_spp_apis.d 


# Each subdirectory must supply rules for building sources it contributes
sapis/bt_ble/rsi_ble_gap_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_ble_gap_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_ble_gap_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_ble_gatt_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_ble_gatt_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_ble_gatt_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_ble_l2cap_conn.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_ble_l2cap_conn.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_ble_l2cap_conn.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_bt_a2dp_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_a2dp_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_bt_a2dp_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_bt_avrcp_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_avrcp_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_bt_avrcp_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_bt_common_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_common_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_bt_common_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_bt_gap_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_gap_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_bt_gap_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_bt_hfp_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_hfp_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_bt_hfp_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_bt_hid_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_hid_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_bt_hid_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_bt_iap_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_iap_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_bt_iap_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_bt_pbap_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_pbap_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_bt_pbap_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_bt_sdp_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_sdp_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_bt_sdp_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
sapis/bt_ble/rsi_bt_spp_apis.o: C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/bt_ble/rsi_bt_spp_apis.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DRSI_DEBUG_PRINTS -DRSI_SPI_HIGH_SPEED_ENABLE -DRSI_SPI_INTERFACE -DRSI_SAMPLE_HAL -DRSI_BT_ENABLE -DRSI_BLE_ENABLE -DRSI_WLAN_ENABLE -DSTM32_PROJECTS -DRSI_PUF_ENABLE -DUSE_HAL_DRIVER -DSTM32F411xE -DDEBUG -c -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/utilities/certificates" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/examples/master_application" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Drivers/CMSIS/Include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/platforms/STM32/Reference_Projects/Cube_Baremetal/Core/Inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/common" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/crypto" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/include" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/aws_sdk/platform/inc" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/http_server" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mdnsd_records" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications/mqtt_client/src/MQTTPacket/src" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/nwk/applications" -I"C:/Users/daclark/Desktop/redpine/RS9116.NB0.WC.GENR.OSI.2.0.0.0024/host/sapis/rom" -O0 -ffunction-sections -fdata-sections -fstack-usage -MMD -MP -MF"sapis/bt_ble/rsi_bt_spp_apis.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

