################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_interface.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_json.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_topics.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_types.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_json_utils.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_common_internal.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_connect.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_publish.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_subscribe.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_unsubscribe.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_yield.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_shadow.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_actions.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_json.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_records.c \
C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/jsmn.c 

OBJS += \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_interface.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_json.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_topics.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_types.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_json_utils.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_common_internal.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_connect.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_publish.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_subscribe.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_unsubscribe.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_yield.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_actions.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_json.o \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_records.o \
./Sapis/nwk/applications/aws_sdk/src/jsmn.o 

C_DEPS += \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_interface.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_json.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_topics.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_types.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_json_utils.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_common_internal.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_connect.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_publish.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_subscribe.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_unsubscribe.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_yield.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_actions.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_json.d \
./Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_records.d \
./Sapis/nwk/applications/aws_sdk/src/jsmn.d 


# Each subdirectory must supply rules for building sources it contributes
Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_interface.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_interface.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_interface.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_interface.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_json.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_json.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_json.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_json.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_topics.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_topics.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_topics.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_topics.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_types.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_types.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_types.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_jobs_types.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_json_utils.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_json_utils.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_json_utils.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_json_utils.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_common_internal.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_common_internal.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_common_internal.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_common_internal.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_connect.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_connect.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_connect.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_connect.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_publish.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_publish.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_publish.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_publish.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_subscribe.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_subscribe.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_subscribe.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_subscribe.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_unsubscribe.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_unsubscribe.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_unsubscribe.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_unsubscribe.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_yield.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_yield.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_yield.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_mqtt_client_yield.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_shadow.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_actions.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_actions.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_actions.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_actions.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_json.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_json.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_json.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_json.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_records.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_records.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_records.d" -MT"Sapis/nwk/applications/aws_sdk/src/aws_iot_shadow_records.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Sapis/nwk/applications/aws_sdk/src/jsmn.o: C:/Users/jokolapu/Desktop/test/host/sapis/nwk/applications/aws_sdk/src/jsmn.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-DEFM32GG11B820F2048GL192=1' '-DUSE_HAL_DRIVER=1' '-DRSI_SPI_INTERFACE=1' '-DRSI_SAMPLE_HAL=1' '-DRSI_WLAN_ENABLE=1' '-DRSI_DEBUG_PRINTS=1' '-DRSI_BT_ENABLE=1' '-DRSI_BLE_ENABLE=1' -I"C:/Users/jokolapu/Desktop/test/host/platforms/EFM32/Reference_projects/Simplicity/Projects/SPI/AWS_IoT/hal-config" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\wlan\cloud\aws_iot\device_shadow" -I"C:\Users\jokolapu\Desktop\test\host\sapis\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\rom" -I"C:\Users\jokolapu\Desktop\test\host\sapis\examples\utilities\certificates" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mdnsd_records" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\mqtt_client\src\MQTTPacket\src" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\include" -I"C:\Users\jokolapu\Desktop\test\host\sapis\nwk\applications\aws_sdk\platform\inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/halconfig/inc/hal-config" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/halconfig" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/emlib/inc" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//hardware/kit/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.0//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"C:\Users\jokolapu\Desktop\test\host\platforms\EFM32\hal" -O0 -Wall -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"Sapis/nwk/applications/aws_sdk/src/jsmn.d" -MT"Sapis/nwk/applications/aws_sdk/src/jsmn.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


